### ISSUE TITLE
Fatal error: The application will exit now.

### ISSUE THREAD

**Issue by twenty-one** [iina/iina#3266]
Why does the error keep happening?

Error
Fatal error: video info not available
The application will exit now.

When I attempt to play videos that are on a local server, I get this message. Sometimes it happens when I open a second video. Sometimes I get it after several are open and I open an additional video.

When it happens, the app closes and all the windows close, not just the most recent that seems to have caused the problem.

I have not figured out how to avoid this issue nor how to stop the app from closing all the open videos when it seems that only the most recent one I attempted to open caused the problem.

Afterwards, I can open the supposedly problematic video with no problem, but I never know when it will occur again.

I'm running on an iMac with lots 64GB RAM, MacOS Catalina Version 10.15.7. I'm running IINA 1.1.2 Build 128.

- macOS MacOS Catalina Version 10.15.7.
- IINA IINA 1.1.2 Build 128.

It seems that this happens when the videos are on a NAS, although I haven't tried it on the internal SSD with a lot of files.

**Comment by luckydonald** [comment]
Happened to me with Youtube too, back when that worked.

**Comment by low-batt** [comment]
The fix in PR #3434 has been merged into the develop branch.

See issue #3013 for details.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.

**Comment by brandonjp** [comment]
This just started for me today with version 1.4.0
Have uninstalled/reinstalled via Homebrew. 

I don't see any info on the referenced tickets on ways to solve this on my end. 
Any suggestions?


Still getting:
```
Fatal error: Cannot get user config file! 
The application will exit now.
```

<img width="280" height="230" alt="Image" src="https://github.com/user-attachments/assets/f6a85dfb-8cf8-4bee-beaa-136f17aad735" />

**Comment by low-batt** [comment]
This is not the problem discussed in this issue. I don't recall anyone reporting hitting this.

IINA stores some data in the standard macOS location, `/Users/<your username>/Library/Application Support/com.colliderli.iina`. Under that directory is a sub-directory `input_conf` as seen here:
```text
low-batt@gag com.colliderli.iina$ pwd
/Users/low-batt/Library/Application Support/com.colliderli.iina
low-batt@gag com.colliderli.iina$ ls
bin		history.plist	input_conf	plugins		watch_later
```

Stored in the `input_conf` directory are `.conf` files that are key bindings you have configured.

This is the code that is displaying the fatal alert:
```swift
  static var userConfigs: [String: String] {
    do {
      let files = try fm.contentsOfDirectory(at: Utility.userInputConfDirURL, includingPropertiesForKeys: nil)
      let configFiles = files.filter { $0.pathExtension == "conf" }
      return Dictionary(uniqueKeysWithValues: configFiles.map { ($0.deletingPathExtension().lastPathComponent, $0.path) })
    } catch {
      Logger.fatal("Cannot get user config file!")
    }
  }
```

That code is reading the user configured key bindings stored in that directory. Something is going wrong while reading those files.

Check that directory. See what is there. Look at the `.conf` files. Do they look malformed in some way?

I'm confused as to how IINA got into this bad state.
