### ISSUE TITLE
IINA seek is slow and requires almost a second to resume playback.

### ISSUE THREAD

**Issue by bbajr** [iina/iina#4305]
**System and IINA version:**
- macOS: Ventura 13.3 on macbook air m1 2020
- IINA: 1.3.1

**Expected behavior:**
Previously, when I pressed left and right on keypad, the seek of -+5 sec was instant without any barely noticeable delay.

**Actual behavior:**
Currently, when I press left and right, there is almost a second delay between seek and video playback.

**Steps to reproduce**
Play any video and try seek by pressing left and right for -+5 second seek.
The problem exists regardless of the seek duration and for both options: exact and keyframe seek.

MPV does not have this problem.

**How often does this happen?**
Always.

**Comment by low-batt** [comment]
There is more than one known problem that could be responsible for this.

There is a problem with lagging when using Bluetooth audio devices. That is an upstream problem in mpv that has been fixed in mpv 0.35.1. IINA will be upgrading mpv to pickup that fix. My guess is that is not what you are reporting.

I'm expecting this is the problem reported in issue #4153. A fix for that problem is currently being reviewed.

**Comment by bbajr** [comment]
Wow. You are absolutely right. It only happens when I use my Bluetooth headset. 
Lags not there when I use laptop speaker.
Thank you. I will be waiting for next release with updated mpv build

**Comment by low-batt** [comment]
I guessed wrong! There are several issues reporting the wireless audio issue. I'll mark this as a duplicate of issue #3805. The mpv issue is https://github.com/mpv-player/mpv/issues/10270. I tested my Bluetooth speakers with IINA built with mpv 0.35.1 and seeking was faster.

Fixes are currently being reviewed and merge in preparation for a new release, which will include upgrading mpv and FFmpeg.

**Comment by ghost** [comment]
@low-batt I am using nightly and the problem persists. Would you confirm that libmpv has been updated for nightly?

```
2023-04-11 18:26:53 | 869eaaf
```

**Comment by low-batt** [comment]
Thanks for testing the nightly build.

The libraries used by IINA have to be built for both Intel and Apple Silicon, combined into universal binaries and tested. Several developers are working on building a new set of upgraded dependencies right at this moment. This includes upgrading to mpv 0.35.1, patched with a fix that was made after that release. The mpv version is listed on the IINA about window. It is in a small font under the IINA version number. When you see it is 0.35.1 in the nightly build then this problem should be fixed. If we remember to do it the issues fixed by the upgrade will be tabled with `progress: fixed/implemented`. The team is focused right now on upgrading the dependencies so this should happen soon.

**Comment by plasmacel** [comment]
Any update on this?

**Comment by low-batt** [comment]
I've been very busy and failed to close this issue with a status of fixed in IINA 1.3.4.

Are you using 1.3.4? If so, what are you experiencing?

**Comment by SebastianEShelby** [comment]
> I've been very busy and failed to close this issue with a status of fixed in IINA 1.3.4.
> 
> Are you using 1.3.4? If so, what are you experiencing?

This started happening to me less than a month ago. I didn't have this issue before.

**Comment by JohnnyFireOne** [comment]
count me in, but mpv and infuse works without issues for some reason, im using macOS 26.1 beta 3
