### ISSUE TITLE
Subtitle blur styling doesn't work with 'override level: force' setting

### ISSUE THREAD

**Issue by sagieinav** [iina/iina#5174]
**System and IINA version:**
- macOS: Sonoma 14.6.1
- IINA: 1.3.5 build 141

**Expected behavior:**
When using the 'force' override setting and any blur styling is set, subtitles should have their borders and shadow offset blurred, like they appear in 'strip' override setting.

**Actual behavior:**
When using the 'force' override setting and any blur styling is set, subtitles DO NOT have their borders and shadow offset blurred.

**Steps to reproduce:**
1. Set custom subtitle styling. Set 'Blur' to any number above zero.
2. Set any border size and shadow offset (better to set a large size for a clearer result)
3. Set subtitle override level to 'force' to reproduce the issue, or set to 'strip' to get correct styling behavior.

**How often does this happen?**
It's permanent.

**I'm not sure if it's a bug or not, but as the 'force' override level can actually force the desired font, size, borders, shadow, and colors -  I assume it isn't impossible for it to also apply the blur to the borders and shadow offset it applies.**

Right now to actually get the blur effect, it's only possible to use 'strip' mode, which doesn't process non-main subtitles well, so I'm refrained from using it.

**Attached below are 4 screenshots.**
First two are a comparison of what I'm running. one with the faulty styling behavior of 'force' mode, and one with the desired styling behavior of 'strip' mode.
The other two are the same comparison, but with intentionally big borders for a clearer comparison.

![CleanShot 2024-09-14 at 07 27 45@2x](https://github.com/user-attachments/assets/5dea12e8-3c0c-486d-b044-aa6fc28544d9)
![CleanShot 2024-09-14 at 07 26 53@2x](https://github.com/user-attachments/assets/db296c86-51b0-4c03-80ed-fcd2f5b4a872)

![CleanShot 2024-09-14 at 07 28 46@2x](https://github.com/user-attachments/assets/221cb33b-3d3a-459f-8f0c-59f5d6a56722)
![CleanShot 2024-09-14 at 07 28 35@2x](https://github.com/user-attachments/assets/5306e53c-f78f-4787-911a-12cd5eae7a1d)

**Comment by low-batt** [comment]
Thank you for the very clear and detailed report. The problem reproduced for me.

For audio/video playback and subtitle rendering support IINA is using a library from the [mpv](https://github.com/mpv-player/mpv) project. Subtitle rendering is performed by `libmpv`.

In IINA 1.3.5 there are known problems with IINA's `Override level` setting. Those problems are due to issues in both IINA and mpv. These problems have been fixed in the current development version of IINA.

_However_ this problem with a blur factor not being applied to the sub font border when the level is set to `force` had not been reported. This behavior is still present in the latest development version of IINA. Very helpful that you took the time to report it.

I have reproduced the problem using the [mpv player](https://github.com/mpv-player/mpv) and reported into the mpv project in issue https://github.com/mpv-player/mpv/issues/14852. We will have to see what they say, but by my interpretation of the mpv documentation for [sub-ass-override](https://mpv.io/manual/master/#options-sub-ass-override) the blur factor should have been applied with the level set to `force`.

**Comment by sagieinav** [comment]
Hi, thank you for responding and issuing this so quickly!

**Comment by sagieinav** [comment]
Thanks you for responding and issuing this so quickly!

**Comment by sagieinav** [comment]
Letting you know that the issue still persists on v.1.4.0-beta1 Build 152.

![Image](https://github.com/user-attachments/assets/0db0fcc1-8625-4d52-81c8-81476722af5a)

![Image](https://github.com/user-attachments/assets/df8e0b27-2846-4846-bc6d-0df22867c70e)

**Comment by low-batt** [comment]
IINA 1.4.0-beta1 provides full direct control over the mpv [sub-ass-override](https://mpv.io/manual/stable/#options-sub-ass-override) option, whereas IINA 1.3.5 would never let you set this option to `no` and was missing the `scale` value. So this is now all about what functionality mpv provides.

The mpv issue https://github.com/mpv-player/mpv/issues/14852 is now closed because mpv has made the changes needed so that blur will be applied when `sub-ass-override` is set to `force`. _However_ those changes do not take effect unless mpv detects that the version of [libass](https://github.com/libass/libass) being used supports the new `ASS_OVERRIDE_BIT_BLUR` setting. There is an extensive discussion about this new setting in the libass PR https://github.com/libass/libass/pull/827. That PR was merged into libass master on Nov 2, 2024. The latest libass release is 0.17.3 from Jul 2, 2024. So the latest release of libass is missing this enhancement.

The next step in getting this fixed is for libass to issue a new release containing the new feature required for this to work. Then IINA will need to upgrade to that version of libass.

**Comment by sagieinav** [comment]
I understand. I can now see that libass' new release, 0.17.4, features the required `ASS_OVERRIDE_BIT_BLUR` flag. Does this allow for this issue to now be fixed in IINA's side?

**Comment by low-batt** [comment]
It requires IINA to upgrade the libraries IINA is built on top of to the latest versions. Too often when we do that we find regressions and have to report the problem to other projects and hopefully obtain fixes. So we only upgrade when we have time to deal with problems. Due to changes in macOS Tahoe breaking IINA, version 1.4.0 was rushed out with quick fixes for critical macOS Tahoe problems. As can be seen from the incoming issues 1.4.0 needed one more beta release. So a 1..4.1 release is planned to address regressions before moving onto 1.5.0. All of the libraries IINA is dependent upon will be upgraded for 1.5.0. At least this is the current plan. We definitely want to upgrade libraries as that should fix a number of problems.

So yes, this issue should be fixed in 1.5.0.

**Comment by low-batt** [comment]
The libraries IINA is dependent upon have been upgraded in the development version of IINA by  PR #6261. This includes upgrading to libass 0.17.5:
```text
18:12:30.768 [iina][d] IINA 1.5.0 Build 167 DEBUG
18:12:30.769 [iina][d] Copyright © 2017-2026
18:12:30.769 [iina][d] Collider LI, et al.
18:12:30.769 [iina][d] Released under GPLv3.
18:12:30.771 [iina][d] mpv v0.41.0
18:12:30.771 [iina][d] FFmpeg 9.0.1
18:12:30.771 [iina][d]   libavcodec 63.1.101
18:12:30.771 [iina][d]   libavformat 63.1.101
18:12:30.771 [iina][d]   libavutil 61.1.101
18:12:30.771 [iina][d]   libswscale 10.1.101
18:12:30.771 [iina][d] libass 0.17.5
18:12:30.772 [iina][d] Built using Xcode 26.3 and macOS SDK 26.2 on Aug 19, 2026 at 6:09:21 PM
18:12:30.772 [iina][d] From branch develop, commit bd5bd3e193e812b1cc6b171cc19b3aa422645c48
18:12:30.773 [iina][d] Running under macOS Version 15.7.4 (Build 24G517)
18:12:30.773 [iina][d] On a MacBookPro18,2 with an Apple M1 Max processor and 64 GiB of RAM
```

I have confirmed that with the development version of IINA, blur is applied with the ASS subtitle override level set to `force`:

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/16a99074-0180-4120-8606-3b3e0b50f979" />

IINA is now following GitHub's practice of closing issues when they are fixed in the development version of IINA, so I am closing this issue as fixed by PR #6261. This fix will be included in the IINA 1.5.0 release.

We are still working on major changes for IINA 1.5.0, so it will be a while before 1.5.0 will be released.
