### ISSUE TITLE
Dim DV HDR video playback with Rec. 709 or Rec. 2020 color space on MacBook Air M1 (2020) running MacOS Sequoia 15.0.1

### ISSUE THREAD

**Issue by mafiefa02** [iina/iina#5218]
# Specifications:
Device used is a 13-inch MacBook Air M1 (2020). Here are the versions used:
- **IINA Version**: `1.3.5 Build 141`
- **mpv Version**: `mpv 0.35.0-419-gf79458476b-dirty`
- **FFmpeg Version**: `6.0`
- **macOS Version**: `15.0.1`
- **Release Channel**: `Release`

# Steps to reproduce
1. Set device's display color space to `Rec. ITU-R BT.709-5` or `Rec. ITU-R BT.2020-1`.
2. Open a video with Dolby Vision and HDR with 4K quality.
3. Make sure to enable HDR in video panel.

# Expected behaviour
This is how I expected the video to look:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/05a3eb05-1ade-4ab8-9dd0-6bd328b8a58d">

# Actual behaviour
This is how the video actually looked with `Rec. ITU-R BT.709-5` color space:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/189c81f1-1a65-4b70-83da-0b43b990dce1">

# How often is the issue reproduceable?
Everytime with a 4K DV HDR video file

# Required/optional actions
- [x] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.
- [x] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.
- [ ] I tested with the Nightly build and confirmed the issue is not fixed.

**Comment by low-batt** [comment]
Reproduced for me using the video [HDR10 - Sony Bravia OLED](https://www.demolandia.net/downloads.html?id=654828652) from [Demolandia](https://www.demolandia.net/).

For audio and video support IINA uses a library from the [mpv project](https://github.com/mpv-player/mpv). This is why the issue template asks if the problem is reproducible with the [mpv player](https://mpv.io/). If the mpv player also exhibits the problem then it is in code not controled by the IINA project and needs to be reported to the mpv project and fixed by them.

Trying mpv with GPU Next and enabling HDR like so:
`mpv --target-colorspace-hint --vo=gpu-next`

I'm seeing the same darkness. I will need to ask the mpv project about this.

**Comment by mafiefa02** [comment]
I'm pretty sure I tested it with mpv, but I might get the settings wrong that time. Alright thanks! Looking forward to hear more about the solution.

**Comment by low-batt** [comment]
It did not reproduce for me as well, when I just ran mpv without any options. It is likely the problem is related to [Extended Dynamic Range](https://developer.apple.com/documentation/metal/hdr_content/displaying_hdr_content_in_a_metal_layer#3335505). To get mpv to use EDR I applied the two options I showed above. That caused the picture to go dark.

**Comment by mafiefa02** [comment]
A little update, I recently upgraded to macOS Sequoia 15.1 (24B83), and the issue still persists. I'm sorry I can't be of much help since I'm not really familiar with mpv and other video stuff. Anyway thanks a lot!
