### ISSUE TITLE
av1 hardware decoding not work on Apple M4

### ISSUE THREAD

**Issue by darkaforest** [iina/iina#5383]
### IINA Version

1.3.5 Build 141

### Release Channel

Release

### macOS Version

15.3.1

### Steps to Reproduce

- Play an av1 encoded video using IINA, example https://www.youtube.com/watch?v=zCLOJ9j1k2Y

### Expected Behavior

using hardware decoding

### Actual Behavior

not using hardware decoding, can confirm that chrome and quicktime are using hardware decoding

### How often can you reproduce the issue

everytime

### Required Actions

- [x] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [ ] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by low-batt** [comment]
The primary issue that covers this is #3241. You will find some discussion of AV1 hardware decoding in comments at the end.

Briefly, the hold up on supporting AV1 hardware decoding was FFmpeg ticket [#10642](https://trac.ffmpeg.org/ticket/10642). That ticket was addressed in commit [f9c5c53](https://github.com/FFmpeg/FFmpeg/commit/f9c5c5358cfef3847674c6f3b3ded9611ebc5647) in October 2024. I'm having trouble finding it, but I think that commit was included in FFmpeg 7.1.1. Pretty sure it is not in 7.1.

IINA 1.3.5 is using FFmpeg 6.0. You can see this on IINA's about window. 

The next release of IINA is a major release that includes lots of risky changes and will use beta releases. That release has been in final testing since November. We keep finding regressions that we judge need to be fixed before the beta can go out the door. Unless something else is found we are down to one known problem outstanding.

The development version of IINA is using mpv 0.38.0 and FFmpeg 7.0.1. This time upgrading dependencies introduced quite a few regressions requiring a lot of time to track down and address. I already know of a fix for an important problem I had been waiting for that is in FFmpeg 7.1, so an upgrade is very desirable. But we are too far into the development cycle to be making major changes at this point. We are currently looking to postpone many issues that were planned for the second beta to speed up the beta cycle and get to the final release. I'm sure we will be upgrading dependencies again after that.

**Comment by database64128** [comment]
On my 2024 M3 MacBook Air, AV1 hardware decoding does not work with mpv 0.40.0 and ffmpeg 7.1.1.

> Briefly, the hold up on supporting AV1 hardware decoding was FFmpeg ticket [#10642](https://trac.ffmpeg.org/ticket/10642). That ticket was addressed in commit [f9c5c53](https://github.com/FFmpeg/FFmpeg/commit/f9c5c5358cfef3847674c6f3b3ded9611ebc5647) in October 2024. I'm having trouble finding it, but I think that commit was included in FFmpeg 7.1.1. Pretty sure it is not in 7.1.

I checked the `release/7.1` branch, and the `libavcodec/videotoolbox_av1.c` file added by FFmpeg/FFmpeg@f9c5c5358cfef3847674c6f3b3ded9611ebc5647 is not there. We probably need to wait until FFmpeg 7.2 for AV1 hardware decoding with `videotoolbox` to work.

**Comment by low-batt** [comment]
Thanks for checking and reporting the state of the FFmpeg fix. Recently there was another important FFmpeg ticket fixed that IINA was tracking. That one isn't in a release yet either. Hopefully 7.2 will contain these fixes and have been released by the time IINA is upgrading dependencies again.

The 1.4.0-beta1 is using mpv 0.38.0 (plus patches) and FFmpeg 7.0.1. At this time the plan is to release 1.4.0 with those versions. The dependencies will be upgraded again once the official 1.4.0 release happens. Before that beta2 needs to be finished and released.

**Comment by jadenquinn** [comment]
> Thanks for checking and reporting the state of the FFmpeg fix. Recently there was another important FFmpeg ticket fixed that IINA was tracking. That one isn't in a release yet either. Hopefully 7.2 will contain these fixes and have been released by the time IINA is upgrading dependencies again.
> 
> The 1.4.0-beta1 is using mpv 0.38.0 (plus patches) and FFmpeg 7.0.1. At this time the plan is to release 1.4.0 with those versions. The dependencies will be upgraded again once the official 1.4.0 release happens. Before that beta2 needs to be finished and released.

So this basically means that the nightly build I have that was built on the fifth is still not doing hwaccel decoding of AV1?

**Comment by low-batt** [comment]
> So this basically means that the nightly build I have that was built on the fifth is still not doing hwaccel decoding of AV1?

Correct. The libraries IINA is dependent upon are built from sources by the IINA project. That build is not automated. If it was, history indicates that build would be broken a lot of the time. The current process is that when IINA decides to upgrade dependencies a developer starts trying to get the dependency build working. Once the build successfully generates libraries we then have to find any changes that need to be made to IINA in order to be compatible with the updated libraries. Generally it is changes in mpv or FFmpeg that require IINA sources to be changed to build and work with the new versions. If nothing else there are IINA sources that are generated based on the mpv version being used. That generation process needs to be run and the new generated IINA sources committed to GitHub. This sometimes requires the generator to be updated. Once we have updated libraries they are uploaded to IINA's server. Builds download these libraries using the script `download_libs.sh` found in IINA's sources.

As much as possible IINA sticks to released versions of the dependencies as that makes it easier to track down problems. With mpv we will apply patches if testing with the upgraded dependencies uncovers regressions. That was the case this time. The `libmpv` IINA 1.4.0-beta1 is using is 0.38.0 + 18 commits. It required quite a bit of time to change IINA's sources.

As the latest versions of dependencies contain fixes for issues IINA has been tracking it is desirable to upgrade dependencies. But we don't want to pickup any new regressions at this point in the development of 1.4.0. The plan for 1.4.0-beta2 is to fix the regressions found in testing beta1, fix problems in the new functionality added and add a limited amount of new features that are deemed less likely to introduce problems. While we are working to get 1.4.0 out the door the nightly build will reflect the latest 1.4.0 development.

I'm hoping that by the time IINA is ready to upgrade dependencies FFmpeg will have released a version with AV1 hardware decoding support.

**Comment by low-batt** [comment]
FFmpeg 8 has been released with support for AV1 hardware decoding. Unless some severe regressions in FFmpeg are encountered, the next time IINA upgrades dependencies AV1 hardware decoding will work on Macs with chips that support it.

**Comment by karpovpw** [comment]
Hi! So, is it working now?

**Comment by low-batt** [comment]
Building the libraries IINA is dependent upon is non-trivial. The usual problem is that other projects have made changes that break things under the old versions of macOS IINA is trying to support. We have successfully built upgraded libraries for Apple Silicon, but are encountering problems trying to build libraries for Intel Macs running macOS 10.15. In the meantime we are working on IINA 1.4.2 to fix additional regressions. The upgraded libraries will be in IINA 1.5.0. So far that includes FFmpeg 8 which has the AV1 hardware decoding.

**Comment by jadenquinn** [comment]
> Hi! So, is it working now?

Yes, but you might need the beta build...? Idk. works for me, but it uses still way more CPU and GPU than QuickTimePlayer does, but then again, IINA always does that. It is using VT though.

**Comment by karpovpw** [comment]
> Building the libraries IINA is dependent upon is non-trivial. The usual problem is that other projects have made changes that break things under the old versions of macOS IINA is trying to support. We have successfully built upgraded libraries for Apple Silicon, but are encountering problems trying to build libraries for Intel Macs running macOS 10.15. In the meantime we are working on IINA 1.4.2 to fix additional regressions. The upgraded libraries will be in IINA 1.5.0. So far that includes FFmpeg 8 which has the AV1 hardware decoding.

I understand and I thank you from the bottom of my heart for your hard work! Will wait for 1.5.0 and can test it on my M3 Pro when available.

**Comment by uiryuu** [comment]
Fixed in https://github.com/iina/iina/pull/6261
