### ISSUE TITLE
Videos Stutter on macOS 26 Tahoe

### ISSUE THREAD

**Issue by farrukhaskari1** [iina/iina#5732]
### IINA Version

1.4.1

### Release Channel

Release

### macOS Version

macOS 26 Tahoe

### Steps to Reproduce

- Playing any video it stutters

### Expected Behavior

shouldn't stutter.

### Actual Behavior

mid video the player stutters in playing video. this is happening to every video that's being played

### How often can you reproduce the issue

everytime

### Required Actions

- [x] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [ ] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by low-batt** [comment]
@askari01 Thanks for the report.

Unfortunately it is not reproducing for me. Apple broke a _lot_ of things in macOS Tahoe. This might be one of them.

Performance problems / lagging are  very sensitive to all of the technical details such as the exact characteristics of the Mac IINA is running on, the details of how the video being played is encoded, etc. Without the IINA and mpv log files it is hard to even get started. See the FAQ:  [How to collect log files when reporting an issue?](https://github.com/iina/iina/wiki/FAQ#how-to-collect-log-files-when-reporting-an-issue)

Do you have any "helper" apps, the kind that intercept macOS events to allow control over the position of windows, actions when window buttons are pressed, etc.? Such tools can introduce lagging. An example of such an app is [BetterTouchTool](https://folivora.ai/). I'm running that one without problems under macOS 26, but other such tools have been responsible for lagging in the past.

I tested playing an AV1 encoded downloaded copy of the YouTube video [Big Buck Bunny 60fps 4K](https://www.youtube.com/watch?v=aqz-KE-bpKQ). Does that video exhibit stuttering when you play it?

These messages from the IINA log file show details of the Mac I ran the test on:
```text
12:05:30.365 [iina][d] Running under macOS Version 26.0.1 (Build 25A362)
12:05:30.365 [iina][d] On a MacBookPro16,1 with an Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz processor
```

This MacBook is from 2019. If you supply logs I will be able to compare it to the Mac you are using.

Overall macOS 26 feels very laggy to me. I notice pauses opening Apple Apps. The removal of Launchpad makes macOS Tahoe a huge downgrade for me.

**Comment by farrukhaskari1** [comment]
i will get the log and will try to present it in a better way, yeah I feel the same about this open issue. I will post soon in a couple of days. If Tahoe is bad, wait until you see iOS... I dont have an attachment to launchpad it was made ugly in recent years like it never matched the design philosophy of the OS, it looked like iPadOS thingy. coming from raycast the super imposed spotlight is bit odd at first. like do I need a spotlight or will it open the spotlight with menu... is kind of hit and miss for me.

**Comment by OberstKrueger** [comment]
My anecdotal experience so far is that IINA seems much more sensitive to overall system resource usage than on macOS 15. Moreso, if something happens that derails the playback performance, the only thing that fixes it is to let the video player for 30-60 seconds or restarting the whole application.

A specific example of this was while watching a 4k60 video without issue on my M1 Max MBP, I started up another CPU intensive task (ImageOptim optimizing one file, but it spread across all 10 cores). The video stopped playing, and audio stuttered to the point where I could not understand what was being said. When the CPU intensive task ended, the audio returned to normal but the video continued to play at roughly 5-10 FPS. Previous macOS versions, this would cause varying levels of dropped frames, but audio would play fine.

I will try and sit down this weekend to get logs to see if there's anything insightful within them, but wanted to throw my experience in for now until I can get more concrete data on it.

**Comment by low-batt** [comment]
I smashed my hands. Painful to type at the moment. Have to keep this short…

The next time you get IINA into this state follow these instructions:
- **Do not** shutdown IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Video/Audio`
- Scroll down to the `Audio` section
- Change the `Audio driver` setting to a different driver
- **Do not** shutdown IINA
- Once audio restarts see if video plays normally
- Repeat, switching back to original driver
- Does it play normally?
- Collect log files, attach them here and report behavior

![Image](https://github.com/user-attachments/assets/122f1579-b913-4f0d-b18c-8362d023c44c)

I have not encountered the behavior described, but I did get IINA into a state where video would experience an unexpected pause every once in a while, with audio playing fine. This was not under macOS 26. I'm starting to think this is a mpv problem. With log files I should be able to confirm if this issue is a worse case of what I experienced or something else.

Due to other critical problems we are currently working on upgrading mpv, FFmpeg and other libraries to obtain fixes.

**Comment by farrukhaskari1** [comment]
[iina.log](https://github.com/user-attachments/files/22711663/iina.log)
[mpv.log](https://github.com/user-attachments/files/22711662/mpv.log)

@low-batt

**Comment by low-batt** [comment]
I took a quick look at the logs. What I was looking for was messages like this in the mpv log:
```text
[78629.321][w][ao/coreaudio] cannot get device latency (jbo[33]/560947818)
[78629.321][w][ao/coreaudio] cannot get device sample rate, falling back to AO sample rate! (jbo[33]/560947818)
```
And especially this:
```text
[80361.481][v][cplayer] blocked, waiting for old audio to play
```

That is from the log when I encountered video lagging.

I did not find these in the attached logs, so it looks like what I hit is a different problem.

**Comment by kasvith** [comment]
@low-batt changing the audio driver seems to fix it on tahoe(1.4.1)

**Comment by farrukhaskari1** [comment]
did you use AFcoundation or Core ? @kasvith

**Comment by kasvith** [comment]
i used AVFoundation

**Comment by low-batt** [comment]
Always have to be cautious about jumping to a conclusion about the root cause of a defect. Normally I resist mentioning my speculations about the cause of a problem, but in this case I think it is useful to discuss one possiblity.

IINA 1.4.x is using a `libmpv` built from mpv 0.38.0 plus quite a few patches to fix some problems found during the upgrade. It is missing the fix for the mpv issue [#14828](https://github.com/mpv-player/mpv/issues/14828). That mpv issue shows these log messages:
```text
[ao/coreaudio] cannot get device latency (jbo[33]/560947818)
[ao/coreaudio] cannot get device sample rate, falling back to AO sample rate!(jbo[33]/560947818)
```

Those are the same log messages I show above. However the mpv issue is not about video lagging, it is about mpv triggering this:
```text
runtime error: nan is outside the range of representable values of type 'long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior audio/out/ao_coreaudio_utils.c:453:12
```

The fix doesn't discuss the implications of this defect. It looks like a random value was being used for the sample rate if mpv was unable to obtain the device's sample rate. In the case reported that caused a nan value to be uses as a divisor and badness ensued. What is not discussed is what else might go wrong due to the use of a random value for sample rate. I think it means mpv will use the wrong latency for the audio device. I am suspicious that this could be the problem I hit with lagging. This message from the lagging problem I hit definitely shows mpv intentionally paused rendering of video:
```text
[80361.481][v][cplayer] blocked, waiting for old audio to play
```

That is about keeping video synchronized with audio. That involves audio device latency.

This mpv problem was specific to the `Core Audio` device driver. Thus if video does not lag using the `AVFoundation` driver, it suggests this mpv defect might be the cause.

When I hit this I switched from the `Core Audio` driver to the `AVFoundation` driver and then back to the `Core Audio` driver. That cleared the problem. I believe when I switched back to the `Core Audio` driver it was able to obtain the device latency, thus avoiding the problem.

Trouble is in the logs from @askari01 I did not find the log message indicating trouble getting the audio device latency. It could be we are dealing with more than one problem.

We are currently upgrading the libraries IINA uses. That includes upgrading to mpv 0.40.0 which includes the fix for mpv issue [#14828](https://github.com/mpv-player/mpv/issues/14828). But I'm worried there is a second problem here that has not been identified.

**Comment by farrukhaskari1** [comment]
CA -> AVFoundation -> CA fixed the problem. no stuttering now. safari was also having issue now its fixed with switching. I can close it now. if everyone agrees.

**Comment by low-batt** [comment]
The report that after switching to the `AVFoundation` audio driver the problem does not reproduce is very helpful.

As this suggests there is a problem with the `Core Audio` driver, we want to leave this issue open until that problem has been tracked down and solved.

**Comment by JacoNeto** [comment]
I have the same issue.

**Comment by JohnnyFireOne** [comment]
@low-batt 

i fix mine by removing .mpv folder cause i was using mpv too. now iina works stable as before!

i reinstall mpv and my .mpv folder settings and now works.... dont what caused that but now IINA works perfectly with MPV config installed (i dont use this for iina settings)

**Comment by kapitainsky** [comment]
> CA -> AVFoundation -> CA fixed the problem. no stuttering now. safari was also having issue now its fixed with switching. I can close it now. if everyone agrees.

It has fixed the same issue for me too. Thx.. 

But it is not 100% smooth. With Audio Core it is impossible to watch. With AVFoundation it is many time better. But not perfect. Comparing the same video with playback on VLC clearly shows some IINA issue.

EDIT: I was too quick to claim success - it is still not watchable for some 4k videos. They used to work without any issues before Tahoe. And work fine with VLC now.
